apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ci-cd-lifeline
description: Deploy pipeline for LifeLine
serialPipeline:
  stages:
  - targetId: run-qsdev
    profiles: [dev]
  # - targetId: run-qsprod
  #   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  location: projects/${PROJECT_ID}/locations/europe-west2
---

# apiVersion: deploy.cloud.google.com/v1
# kind: Target
# metadata:
#   name: run-qsprod
# description: Cloud Run production service
# run:
#   location: projects/${PROJECT_ID}/locations/europe-west2