apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lifeline-qobalt
  namespace: '157934573900'
  selfLink: /apis/serving.knative.dev/v1/namespaces/157934573900/services/lifeline
  labels:
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: europe-west2
  annotations:
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Custom
      annotations:
        run.googleapis.com/client-name: cloud-console
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '4'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 157934573900-compute@developer.gserviceaccount.com
      containers:
      - name: lifeline-1
        image: lifeline-app-image
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
        startupProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 15
  conditions:
  - type: Ready
    status: 'True'
  - type: ConfigurationsReady
    status: 'True'
  - type: RoutesReady
    status: 'True'
  # url: https://lifeline-5l6v7pcxsq-nw.a.run.app
  # address:
  #   url: https://lifeline-5l6v7pcxsq-nw.a.run.app
