replicaCount: 1

image:
  repository: 0x1d1983/lifeline
  pullPolicy: IfNotPresent
  tag: "0.1"

env:
  # "ASPNETCORE_ENVIRONMENT": "Production"
  # "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"
  # "AzureServiceBusConfig__ConnectionString": ""
  # "AzureServiceBusConfig__Topic": "test-topic"
  # "AzureServiceBusConfig__Subscription": "S1"
  # "AzureServiceBusConfig__ReportInterval": "10"
  
service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

autoscaling:
  enabled: false

serviceAccount:
  create: false